X86_32_OBJECTS= \
  x86_32-aaa.bin \
  x86_32-aad.bin \
  x86_32-aam.bin \
  x86_32-aas.bin \
  x86_32-and.bin \
  x86_32-bound.bin \
  x86_32-bsf.bin \
  x86_32-bsr.bin \
  x86_32-bswap.bin \
  x86_32-bt.bin \
  x86_32-btc.bin \
  x86_32-btr.bin \
  x86_32-bts.bin \
  x86_32-call.bin \
  x86_32-cmp.bin \
  x86_32-cmps.bin \
  x86_32-cmpxchg.bin \
  x86_32-daadas.bin \
  x86_32-div.bin \
  x86_32-enter-leave.bin \
  x86_32-idiv.bin \
  x86_32-imul.bin \
  x86_32-int.bin \
  x86_32-jcc.bin \
  x86_32-jmp.bin \
  \
  x86_32-lsahf.bin \
  x86_32-lea.bin \
  x86_32-lods.bin \
  x86_32-loop.bin \
  \
  x86_32-misc.bin \
  x86_32-mov.bin \
  x86_32-movbe.bin \
  x86_32-movs.bin \
  x86_32-movsxz.bin \
  x86_32-mul.bin \
  \
  x86_32-neg.bin \
  x86_32-nop.bin \
  x86_32-not.bin \
  x86_32-or.bin \
  \
  x86_32-pop.bin \
  x86_32-popcnt.bin \
  x86_32-pop16.bin \
  x86_32-popa.bin \
  x86_32-popa16.bin \
  x86_32-popal.bin \
  x86_32-popaw.bin \
  x86_32-push.bin \
  x86_32-pusha.bin \
  x86_32-push16.bin \
  \
  x86_32-rep.bin \
  x86_32-ret.bin \
  x86_32-rotate.bin \
  \
  x86_32-scas.bin \
  x86_32-setcc.bin \
  x86_32-shift.bin \
  x86_32-sub.bin \
  x86_32-sbb.bin \
  \
  x86_32-xadd.bin \
  x86_32-xchg.bin \
  x86_32-xor.bin \
  \
  x86_32-slicing-01.bin \
  x86_32-slicing-02.bin \
  x86_32-gcd.bin \
  \
  x86_32-simulator-00.bin \
  x86_32-simulator-01.bin \
  x86_32-simulator-02.bin \
  x86_32-simulator-03.bin \
  x86_32-simulator-04.bin \
  x86_32-simulator-05.bin \
  x86_32-simulator-06.bin \
  \
  x86_32-simulator-aaa.bin  \
  x86_32-simulator-aad.bin  \
  x86_32-simulator-aam.bin  \
  x86_32-simulator-aas.bin  \
  x86_32-simulator-add.bin  \
  x86_32-simulator-adcsbb.bin  \
  \
  x86_32-simulator-booleans.bin  \
  x86_32-simulator-bound.bin  \
  x86_32-simulator-bsf.bin  \
  x86_32-simulator-bsr.bin  \
  x86_32-simulator-bswap.bin  \
  x86_32-simulator-bt-01.bin  \
  x86_32-simulator-bt-02.bin  \
  x86_32-simulator-btc.bin  \
  x86_32-simulator-btr.bin  \
  x86_32-simulator-bts.bin  \
  \
  x86_32-simulator-CF.bin  \
  x86_32-simulator-call.bin  \
  x86_32-simulator-call-noinit.bin  \
  x86_32-simulator-cbw.bin  \
  x86_32-simulator-cmov.bin  \
  x86_32-simulator-cmps-01.bin  \
  x86_32-simulator-cmps-02.bin  \
  x86_32-simulator-cmpxchg.bin  \
  x86_32-simulator-cwdcdq.bin  \
  \
  x86_32-simulator-daadas.bin  \
  x86_32-simulator-div.bin  \
  \
  x86_32-simulator-enter-leave-01.bin  \
  x86_32-simulator-enter-leave-02.bin  \
  \
  x86_32-simulator-idiv.bin  \
  x86_32-simulator-imul-01.bin  \
  x86_32-simulator-imul-02.bin  \
  x86_32-simulator-imul-03.bin  \
  x86_32-simulator-int.bin \
  x86_32-simulator-int3.bin \
  x86_32-simulator-into-01.bin \
  x86_32-simulator-into-02.bin \
  \
  x86_32-simulator-lsahf.bin \
  x86_32-simulator-lods.bin \
  x86_32-simulator-loop.bin \
  \
  x86_32-simulator-movbe.bin \
  x86_32-simulator-movs.bin \
  x86_32-simulator-movsxz.bin \
  x86_32-simulator-mul.bin \
  \
  x86_32-simulator-neg.bin \
  \
  x86_32-simulator-popcnt.bin \
  x86_32-simulator-pushpop-01.bin \
  x86_32-simulator-pushpop-02.bin \
  x86_32-simulator-pushpop-03.bin \
  x86_32-simulator-pushpop-04.bin  \
  x86_32-simulator-pushpop-05.bin  \
  x86_32-simulator-pushpop-06.bin  \
  x86_32-simulator-pushfpopf.bin  \
  x86_32-simulator-pushapopa.bin  \
  \
  x86_32-simulator-rep-01.bin \
  x86_32-simulator-rep-02.bin \
  x86_32-simulator-rep-03.bin \
  x86_32-simulator-rep-04.bin \
  \
  x86_32-simulator-rotate-01.bin \
  x86_32-simulator-rotate-02.bin \
  x86_32-simulator-rotate-03.bin \
  x86_32-simulator-rotate-04.bin \
  \
  x86_32-simulator-shift-01.bin \
  x86_32-simulator-shift-02.bin \
  x86_32-simulator-shift-03.bin \
  x86_32-simulator-shift-04.bin \
  \
  x86_32-simulator-scas.bin  \
  x86_32-simulator-sub.bin  \
  x86_32-simulator-setcc.bin \
  \
  x86_32-simulator-xadd.bin  \
  x86_32-simulator-xchg.bin  \
  \
  x86_32-cfgrecovery-01.bin \
  x86_32-cfgrecovery-02.bin \
  x86_32-cfgrecovery-03.bin \
  x86_32-cfgrecovery-04.bin \
  x86_32-cfgrecovery-05.bin \
  \
  x86_32-symsim-01.bin \
  \
  x86_32-bug-001.bin \
  \
  ${dummy}

X86_64_OBJECTS= \
  x86_64-and.bin \
  x86_64-bsf.bin \
  x86_64-bsr.bin \
  x86_64-bswap.bin \
  x86_64-btc.bin \
  x86_64-btr.bin \
  x86_64-bt.bin \
  x86_64-bts.bin \
  x86_64-call.bin \
  x86_64-cmp.bin \
  x86_64-cmps.bin \
  x86_64-cmpxchg.bin \
  x86_64-div.bin \
  x86_64-enter-leave.bin \
  x86_64-idiv.bin \
  x86_64-imul.bin \
  x86_64-int.bin \
  x86_64-jcc.bin \
  x86_64-jmp.bin \
  \
  x86_64-lea.bin \
  x86_64-lods.bin \
  x86_64-loop.bin \
  x86_64-lsahf.bin \
  \
  x86_64-misc.bin \
  x86_64-movbe.bin \
  x86_64-mov.bin \
  x86_64-movs.bin \
  x86_64-movsxz.bin \
  x86_64-mul.bin \
  \
  x86_64-neg.bin \
  x86_64-nop.bin \
  x86_64-not.bin \
  x86_64-or.bin \
  \
  x86_64-pop16.bin \
  x86_64-popcnt.bin \
  x86_64-push.bin \
  \
  x86_64-rep.bin \
  x86_64-ret.bin \
  x86_64-rotate.bin \
  \
  x86_64-sbb.bin \
  x86_64-scas.bin \
  x86_64-setcc.bin \
  x86_64-shift.bin \
  x86_64-sub.bin \
  \
  x86_64-xadd.bin \
  x86_64-xchg.bin \
  x86_64-xor.bin \
  \
  x86_64-slicing-01.bin \
  x86_64-slicing-02.bin \
  x86_64-gcd.bin \
  \
  x86_64-simulator-00.bin \
  x86_64-simulator-01.bin \
  x86_64-simulator-02.bin \
  x86_64-simulator-03.bin \
  x86_64-simulator-04.bin \
  x86_64-simulator-05.bin \
  x86_64-simulator-06.bin \
  x86_64-simulator-adcsbb.bin \
  x86_64-simulator-add.bin \
  x86_64-simulator-booleans.bin \
  x86_64-simulator-bsf.bin \
  x86_64-simulator-bsr.bin \
  x86_64-simulator-bswap.bin \
  x86_64-simulator-bt-01.bin \
  x86_64-simulator-bt-02.bin \
  x86_64-simulator-btc.bin \
  x86_64-simulator-btr.bin \
  x86_64-simulator-bts.bin \
  x86_64-simulator-call-noinit.bin \
  x86_64-simulator-call.bin \
  x86_64-simulator-cbw.bin \
  x86_64-simulator-CF.bin \
  x86_64-simulator-cmov.bin \
  x86_64-simulator-cmps-01.bin \
  x86_64-simulator-cmps-02.bin \
  x86_64-simulator-cmpxchg.bin \
  x86_64-simulator-cwdcdq.bin \
  x86_64-simulator-div.bin \
  x86_64-simulator-enter-leave-01.bin \
  x86_64-simulator-enter-leave-02.bin \
  x86_64-simulator-idiv.bin \
  x86_64-simulator-imul-01.bin \
  x86_64-simulator-imul-02.bin \
  x86_64-simulator-imul-03.bin \
  x86_64-simulator-imul.bin \
  x86_64-simulator-int3.bin \
  x86_64-simulator-int.bin \
  x86_64-simulator-lods.bin \
  x86_64-simulator-loop.bin \
  x86_64-simulator-lsahf.bin \
  x86_64-simulator-movbe.bin \
  x86_64-simulator-movs.bin \
  x86_64-simulator-movsxz.bin \
  x86_64-simulator-mul.bin \
  x86_64-simulator-neg.bin \
  x86_64-simulator-popcnt.bin \
  x86_64-simulator-pushfpopf.bin \
  x86_64-simulator-pushpop-01.bin \
  x86_64-simulator-pushpop-02.bin \
  x86_64-simulator-pushpop-03.bin \
  x86_64-simulator-pushpop-04.bin \
  x86_64-simulator-pushpop-05.bin \
  x86_64-simulator-pushpop-06.bin \
  x86_64-simulator-rep-01.bin \
  x86_64-simulator-rep-02.bin \
  x86_64-simulator-rep-03.bin \
  x86_64-simulator-rep-04.bin \
  x86_64-simulator-rotate-01.bin \
  x86_64-simulator-rotate-02.bin \
  x86_64-simulator-rotate-03.bin \
  x86_64-simulator-rotate-04.bin \
  x86_64-simulator-sample-test.bin \
  x86_64-simulator-scas.bin \
  x86_64-simulator-setcc.bin \
  x86_64-simulator-shift-01.bin \
  x86_64-simulator-shift-02.bin \
  x86_64-simulator-shift-03.bin \
  x86_64-simulator-shift-04.bin \
  x86_64-simulator-sub.bin \
  x86_64-simulator-xadd.bin \
  x86_64-simulator-xchg.bin \
  \
  x86_64-cfgrecovery-01.bin \
  x86_64-cfgrecovery-02.bin \
  x86_64-cfgrecovery-03.bin \
  x86_64-cfgrecovery-04.bin \
  x86_64-cfgrecovery-05.bin \
  \
  x86_64-symsim-01.bin \
  \
  x86_64-bug-001.bin \
  \
  ${dummy}

OBJECTS=${X86_32_OBJECTS} ${X86_64_OBJECTS}

all : $(OBJECTS)

x86_32-%.bin : x86_32-%.s x86_32-simulator-header.s x86_32-simulator-end.s 
	@ echo $@
	@ $(CC) -m32 -march=i686 -c $< -o $@

x86_32-%.bin : x86_32-%.c
	@ echo $@
	@ $(CC) -m32 -march=i686 -c $< -o $@

x86_64-%.bin : x86_64-%.s x86_64-simulator-header.s x86_64-simulator-end.s 
	@ echo $@
	@ $(CC) -m64 -march=i686 -c $< -o $@

x86_64-%.bin : x86_64-%.c
	@ echo $@
	@ $(CC) -m64 -march=i686 -c $< -o $@

clean :
	rm -f ${OBJECTS}

