@node References
@chapter References

@table @bibitem
@item GraphViz
Graphviz - Graph Visualization Software. @uref{http://www.graphviz.org/}, 2009.
@item FASM
Tomasz Grysztar. Flat Assembler. @uref{http://flatassembler.net/}, 2014.

@item XDot
Jose Fonseca. @uref{https://github.com/jrfonseca/xdot.py}, 2014.

@c @item EH86
@c E.A. Emerson and J. Halpern. ``Sometimes'' and ``not never'' revisited: on 
@c branching versus linear time. J. ACM 33, pp 151-178, 1986.
@end table

